### ISSUE TITLE
Sonus update issue

### ISSUE THREAD

**Issue by Favna** [himynameisubik/himynameisubik.github.io#1]
After updating Sonus to version 0.0.1-1 Cydia will still say it requires updating all the while "installed package" also says 0.0.1-1. 

Device: iPhone 5s
iOS: 9.3.3

**Comment by himynameisubik** [comment]
Yea I messed something up with the repo. Sorry! Will fix it soon.

//

**Comment by himynameisubik** [comment]
Has been fixed.

**Comment by Favna** [comment]
awe haha! Cool! Well I hope that whenever we get "it" from China you're adding ios 10 support because I'm already there :p
